#!name=iOS Location Spoofer
#!desc=透过 MITM 改写 Apple 定位回应的经纬度。Quantumult X 适用。
#!homepage=https://github.com/mekos2772/ios-location-spoofer

^https?:\/\/(?:gs-loc(?:-cn)?\.apple\.com|bluedot\.is\.autonavi\.com(?:\.gds\.alibabadns\.com)?)\/clls\/wloc(?:\?.*)?$ url script-response-body https://raw.githubusercontent.com/anaer/qx/main/rewrite/apple-wloc.js

hostname = gs-loc.apple.com, gs-loc-cn.apple.com, bluedot.is.autonavi.com, bluedot.is.autonavi.com.gds.alibabadns.com